apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5-alpine
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: "http://localhost:30007"
            # This is the "magic" fix: Ghost needs to know it's in development
            # to use SQLite without complex production config files.
            - name: NODE_ENV
              value: "development"
